### ISSUE TITLE
1.4 will not install 

### ISSUE THREAD

**Issue by paerbac** [OlauncherCF/OlauncherCF#224] opened 2022-12-14 02:35 UTC
Error message when installing: App not installed as package appears to be invalid.

Device: Pixel 7 pro with android 13

**Comment by jooooscha** [comment] 2022-12-14 08:04
This is an issue with the github release action, not with the actual update.

Please refer to #196

Also: Please use the template as intended, and do not just delete everythin. Closing for lack of further information

**Closed** 2022-12-14 08:05 UTC
Labels: bug
