### ISSUE TITLE
"Double tap to lock" only enables correctly if launcher is in English

### ISSUE THREAD

**Issue by eclairevoyant** [OlauncherCF/OlauncherCF#180] opened 2022-09-10 08:03 UTC
#### Short description 
Enabling "double tap to lock" only works when launcher is in English

#### Steps to reproduce
1. Switch launcher language to English
1. Disable "Double tap to lock"
1. Switch launcher language to Chinese
1. Enable "Double tap to lock"

After this, double tapping on the launcher screen **does not** enable screen lock on double-tap.
However, if I switch the order of the last two steps, then screen locking works as expected.
In other words, the launcher needs to be in English when I enable screen locking for it to work.

My guess is the launcher is storing "On" if I enable it in English and "开" when I enable it in Chinese.

#### Environment information
- Olauncher CF Version: 1.2.4
- Install Source: F-Droid
- Device: `sofia`
- Android: Stock ROM, Android 11
- EMUI?: Don't know what this is, so probably not.
- Other: 

#### Additional elements
I reproduced this behaviour both with system language = English as well as system language = Chinese (China).
Therefore system language seems irrelevant here.

**Comment by Npa972** [comment] 2022-09-12 15:54
Double tap looks like a sensitive function. On my phone (cheap xiaomi redmi, french language) sometimes it work perfectly for a long period and sometimes stop working for an unknown reason (at my level). I have to reset the function.
Perhaps it is not a Olauncher's bug. I had the same problem with nova launcher witch i used for a while.

**Comment by eclairevoyant** [comment] 2022-09-13 16:08
@jooooscha as mentioned in the issue description, switching the language isn't what causes the bug. Switching the launcher language to Chinese and _then enabling double tap_ does.
This is consistently reproducible and not temporary.

**Comment by jooooscha** [comment] 2022-09-13 16:51
Yeah, sorry. I misread your description.

Have reproduced it; will investigate

**Comment by tuch96** [comment] 2022-09-16 17:32
@eclairevoyant The app Lock from f-droid could be a temporary solution. After installing it, you can integrate it into one of the right or left swipe functions. Works very well for me!
[https://f-droid.org/packages/name.seguri.android.lock/](https://f-droid.org/packages/name.seguri.android.lock/)

**Comment by jooooscha** [comment] 2022-12-16 13:48
Found it. It was a rather stupid bug, involving a string that was used to match on a certain action. When changing the language, the `if` statement failed, because one side was translated, while the other was not.

Anyway, should be fixed in 2e656dbd8ff7776242dd0b73fdf90171dc88c348

**Closed** 2022-12-16 13:47 UTC
Labels: bug
