### ISSUE TITLE
Sort by recently used

### ISSUE THREAD

**Issue by Donkey-Doug** [OlauncherCF/OlauncherCF#229] opened 2022-12-14 15:12 UTC
- [X] I have searched existing issues for this feature.

#### Motivation behind feature
This way people are more likely to scroll less
...

#### Proposed Feature
Instead of alphabetical, have an option to sort by recently used in the app drawer. Also make it possible to sort by recently used in the homescreen and make sure the apps present on the homescreen are then not repeated in the drawer.
...

**Comment by jooooscha** [comment] 2022-12-14 15:27
duplicate of #56

**Comment by jooooscha** [comment] 2022-12-15 07:54
closing in favor of #231

**Closed** 2022-12-15 07:54 UTC
Labels: feature
