### ISSUE TITLE
2 shadows

### ISSUE THREAD

**Issue by lichingyun** [OlauncherCF/OlauncherCF#218] opened 2022-12-02 18:18 UTC
![115820749-c7445980-a401-11eb-9dd6-0d6af5d4a518](https://user-images.githubusercontent.com/79099214/205358439-137ee0b9-2135-4fa5-a5ea-5e595acba9ed.png)

In Android 11 (Arrow Os 11 e Lineage 18.1) 
the original Olauncher have 2 "shadows" in the upper and the bottom
of the screen. The original developer doesn't know how to remove these "shadows" (I don't know how to name these in english)
I like to know if OCF have the same problem in Android 10 or 11 🙏

Many Thanks

**Comment by jooooscha** [comment] 2022-12-02 20:14
This seems to be android related.
Also, I don't seem to understand your exact problem. Where is the feature description?
Please use the templates as intended, and don't just delete the template.

Closing as off topic

**Closed by jooooscha** 2022-12-02 20:14 UTC
Labels: feature
