### ISSUE TITLE
Weather Widget under clock

### ISSUE THREAD

**Issue by The-Repo-Club** [OlauncherCF/OlauncherCF#222] opened 2022-12-10 01:47 UTC
- [X] I have searched existing issues for this feature.

#### Motivation behind feature

I like the sound of having the weather under the clock

#### Proposed Feature

Text with current weather under the time/date

#### Possible alternatives (if applicable)

n/a but i may work on this myself :)

#### Additional context

![Screenshot_20221210-014419](https://user-images.githubusercontent.com/9284733/206822969-a2c99fb1-ac6e-42a6-8020-014a9ff669dc.png)

**Comment by jooooscha** [comment] 2022-12-10 08:30
duplicate of #113

**Comment by jooooscha** [comment] 2022-12-11 21:31
I have been thinking about it and I don't want to be in the way if someone really wants this. Therefore, I see two options to add this feature:

The first is two compile the app in two versions, one with internet and one without. Problems would be, that we would have to find a weather widget, or api where we get the data from.

The second, and probably more complicated option would be two replace the clock/date with a place to add normal widgets as known from other launchers.
I am not sure of all implications this would have 

I think both are not completely satisfactory in their current respective form. But maybe we find another good solution?

**Comment by The-Repo-Club** [comment] 2022-12-11 21:35
ya i can defo get this working i just need to get a way to get the log and lat without using the playstore location as that would make it so it can not go on the fDroid website

**Comment by The-Repo-Club** [comment] 2022-12-15 09:06
I hope you are ok with me reoping this and maybe adding it in the future. If you are not wishing you have this feature I totally understand that it is your project and I understand that you dont want to need to require internet permission within the app.

**Closed** 2022-12-17 18:05 UTC
Labels: feature
