### ISSUE TITLE
Feature Request Widget Support

### ISSUE THREAD

**Issue by blogmangit** [OlauncherCF/OlauncherCF#257] opened 2022-12-28 08:13 UTC
- [x] I have searched existing issues for this feature.

#### Motivation behind feature

...Widget support will be great. 

#### Proposed Feature

...Adding Widget support will be a great addition. 

#### Possible alternatives (if applicable)

...No Alternatives.

#### Additional context

<details>
  <summary>Context</summary>

Add your long texts or screenshots here

</details>

**Comment by jooooscha** [comment] 2022-12-28 11:16
duplicate of #177

**Closed by jooooscha** 2022-12-28 11:16 UTC
Labels: feature
