### ISSUE TITLE
Add Transition Animations

### ISSUE THREAD

**Issue by FrenchToucan** [OlauncherCF/OlauncherCF#274] opened 2023-01-10 19:32 UTC
### Checklist

- [X] I have searched for existing issues about this feature.
- [X] I know that if existing issues are available, this issue will be closed without comment, unless an explaination is given on why this new issue is needed.

### Motivation

Adds a significant level of polish and enhances the user experience. Just looks cool.

### Feature description

Transition animation present in Pixel Launcher, Nova, Niagara, and many OEM launchers. Example shown here: (deleted, see below)

When swiping away apps, causes the app to zoom into the icon (if it's on the home screen).

More info: https://android.googlesource.com/platform/packages/apps/Launcher3/+/30ac97d9386736c3322a3277f74523497627b9f5

**Comment by jooooscha** [comment] 2023-01-13 13:54
I have several questions to this feature.

First of all, the first link is invalid?

Secondly, what does 
> When swiping away apps

mean. Do you mean, when closing apps?

Thirdly:
>causes the app to zoom into the icon

which Icons, should OlauncherCF zoom into? OlauncherCF does not show the icons of the apps (by design)

**Comment by FrenchToucan** [comment] 2023-01-13 14:28
> I have several questions about this feature.
> 
> First of all, the first link is invalid?
Apologies, try this one: https://twitter.com/prjkt_io/status/1551634957030010881
> 
> Secondly, what does When swiping away apps mean. Do you mean, when closing apps, returning to the home screen (OlauncherCF does not have a normal home screen). 
Yeah, exactly. Swiping up from the bottom to return to the homescreen. The effect that is shown currently is the same as typical launcher that doesn't use the animation API described below.
> 
> Thirdly: causes the app to zoom into the icon
> 
> which Icons should OlauncherCF zoom into? OlauncherCF does not show the icons of the apps (by design)
The commit didn't lead me to believe a proper icon was required for the functionality to work. I'm not an expert (or even an amateur, though).

**Comment by jooooscha** [comment] 2023-01-14 11:26
But without icons, where should the animation be directed at. Maybe, at the text, but most of the applications will probably not be on your home screen, in contrast to other launchers.

**Comment by FrenchToucan** [comment] 2023-01-14 17:42
Yeah, I would say zooming in and out of the text would look great. And I would think users would be mostly using apps on their home screen.

**Comment by jooooscha** [comment] 2023-01-30 18:27
Ok, I tried to implement this with the links you have provided. Unfortunately, the API never gave me any information about the closing app. Also, I could not find a lot of information about the API, therefore, I am not sure what I am doing wrong

**Comment by jooooscha** [comment] 2023-02-18 21:29
As I cannot find any information about how to implement this, I will close this for now. If anyone can help with this I would be happy to accept an PR

**Closed by jooooscha** 2023-02-18 21:29 UTC
Labels: feature
