### ISSUE TITLE
Homescreen shortcuts briefly change to default "App" when opening an app

### ISSUE THREAD

**Issue by Blake-LeBlanc** [OlauncherCF/OlauncherCF#205] opened 2022-11-05 15:21 UTC
#### Short description
Whenever I open an app (usually one of the "larger" apps), the homescreen will briefly flash into view and display the shortcuts with their default "App" names

#### Steps to reproduce
1. First, admire how clean and awesome OlauncherCF is :) You're doing a great job @jooooscha ! 
2. Open app, either by typing or scrolling and selecting
3. If app is not already in memory (recently loaded), it will briefly flash the home screen as described above

#### Environment information
- Olauncher CF Version: 1.2.10
- Install Source: F-Droid
- Device: Moto G Power 2021
- Android: 11
- EMUI: No
- Other: No battery optimization at the time, on full charge. Happens also when batt opt is enabled.

#### Additional elements

Video: 

https://user-images.githubusercontent.com/19244245/200127038-ba95e8be-e234-456b-ae62-c843661180c8.mp4

**Comment by jooooscha** [comment] 2022-11-05 19:18
Thanks for your kind words, and thanks for reporting.

As far as I can tell, there is the choice of either showing the home screen shortly before opening the app, or showing the app list shortly after closing one. And as I cannot see one being better than the other, I see no reason to change this.

The reason, however, that the apps are seemingly replaced by "App" was caused by an inefficient implementation of how the home screen is loaded. It is the same bug as in #200.

It has been fixed in #202, and should be released in the next few days. It's already submitted to f-droid.

**Closed by jooooscha** 2022-11-05 19:18 UTC
Labels: bug

**Comment by Blake-LeBlanc** [comment] 2022-11-05 20:52
Excellent! 👏

Nov 5, 2022 14:18:35 jooooscha ***@***.***>:
