### ISSUE TITLE
[Feature] Support for Webapps

### ISSUE THREAD

**Issue by Terkyz** [OlauncherCF/OlauncherCF#195] opened 2022-09-24 15:22 UTC
**Is your feature request related to a problem? Please describe.** 
Yes, when I try to create a Webapp with both Chromium and Firefox based browsers the created Webapps are not added to the list of apps. 

**Describe the solution you'd like** 
Webapps are added as apps to the list of launcher apps.

**A clear and concise description of what you want to happen.**
When adding the webapp and trying to open it, the browser with which the webapp was created opens and works as in other launchers. 

**Describe alternatives you've considered** 
I think there is not, it is a very basic function that depends on the browser and launcher.

**Additional context**
I have tried NativeAlpha, an app with the specific function to create webapps in containers and it still doesn't work.

- Add any other context or screenshots about the feature request here.
- ඞ.

**Comment by jooooscha** [comment] 2022-09-24 16:29
Duplicate of #157

**Closed by jooooscha** 2022-09-24 16:29 UTC
Labels: feature
